/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.edusys.ui;

import java.awt.Color;
import java.awt.Frame;
import java.awt.event.ActionEvent;
import javax.swing.Timer;

/**
 *
 * @author Admin
 */
public class ChaoDialog extends javax.swing.JDialog {

    /**
     * Creates new form ChaoDialog
     * @param parent
     * @param model
     */
    public ChaoDialog(Frame parent, boolean model) {
        super(parent, model);
        initComponents();
        init();
    }

    private void init() {
        
        this.setLocationRelativeTo(null);
        new Timer(10, (ActionEvent ae) -> {
            int value = progressBar.getValue();
            if (value < 100) {
                value+=1;
                progressBar.setValue(value);
                lblLoading.setText("Loading..."+value+"%");
            } else {
                ChaoDialog.this.dispose();
            }
        }).start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblLoading = new javax.swing.JLabel();
        lbSlogan = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        progressBar = new javax.swing.JProgressBar();
        lblGg = new javax.swing.JLabel();
        lblPhoto = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblLoading.setBackground(new java.awt.Color(204, 204, 204));
        lblLoading.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblLoading.setForeground(new java.awt.Color(255, 255, 255));
        lblLoading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLoading.setText("Loading . . . 0%");
        getContentPane().add(lblLoading, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 760, 30));

        lbSlogan.setBackground(new java.awt.Color(204, 204, 204));
        lbSlogan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbSlogan.setForeground(new java.awt.Color(204, 204, 204));
        lbSlogan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbSlogan.setText("Education Management System");
        getContentPane().add(lbSlogan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 760, -1));

        lblTitle.setFont(new java.awt.Font("Arial Black", 1, 48)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(57, 113, 177));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("EDUSYS");
        getContentPane().add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 760, -1));

        progressBar.setBackground(new java.awt.Color(0, 0, 102));
        progressBar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        progressBar.setForeground(new java.awt.Color(0, 0, 204));
        progressBar.setOpaque(true);
        getContentPane().add(progressBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 760, 30));

        lblGg.setBackground(new Color(0,52,75,200));
        lblGg.setOpaque(true);
        getContentPane().add(lblGg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 400));

        lblPhoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/icons/cdn_PFomp_TT2CHnWmJlr4Nq-526kQGnh1KX.jpg"))); // NOI18N
        getContentPane().add(lblPhoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbSlogan;
    private javax.swing.JLabel lblGg;
    private javax.swing.JLabel lblLoading;
    private javax.swing.JLabel lblPhoto;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JProgressBar progressBar;
    // End of variables declaration//GEN-END:variables
}
