/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.edusys.ui;

import com.edusys.dao.NhanVienDAO;
import com.edusys.entity.NhanVien;
import com.edusys.utils.Auth;
import com.edusys.utils.Contraints;
import com.edusys.utils.MsgBox;
import com.edusys.utils.XImage;
import java.awt.Color;

/**
 *
 * @author Admin
 */
public class DangNhapJDialog extends javax.swing.JDialog {

    /**
     * Creates new form NewJDialog
     *
     * @param parent
     * @param modal
     */
    public DangNhapJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        init();
    }
    
    private void init() {
        this.setLocationRelativeTo(null);
        this.setTitle("HỆ THỐNG QUẢN LÝ ĐÀO TẠO EDUSYS");
        this.setIconImage(XImage.getAppIcon());
        
        pnlPhoto.setBackground(new Color(0, 0, 0, 200));
    }
    
    public DangNhapJDialog() {
    }
    NhanVienDAO dao = new NhanVienDAO();
    
    void login() {
        String manv = txtMaNV.getText().trim();
        String matKhau = new String(txtMatKhau.getPassword()).trim();
        sprMaNV.setBackground(Color.white);
        sprMatKhau.setBackground(Color.white);
        sprMaNV.setForeground(Color.white);
        sprMatKhau.setForeground(Color.white);
        if (manv.isEmpty() || matKhau.isEmpty()) {
            sprMaNV.setBackground(Color.red);
            sprMatKhau.setBackground(Color.red);
            sprMaNV.setForeground(Color.red);
            sprMatKhau.setForeground(Color.red);
            MsgBox.alert(this, "Bạn phải nhập tài khoản và mật khẩu");
            return;
        }
        try {
            NhanVien nhanVien = dao.selectByID(manv);
            if (isLogin(manv, matKhau)) {
                Auth.USER = nhanVien;
                MsgBox.alert(this, "Đăng nhập thành công!");
                this.dispose();
                return;
            } else {
                sprMatKhau.setBackground(Color.red);
                sprMatKhau.setForeground(Color.red);
                MsgBox.alert(this, "Sai mật khẩu!");
                return;
            }
        } catch (NullPointerException e1) {
            sprMaNV.setBackground(Color.red);
            sprMaNV.setForeground(Color.red);
            MsgBox.alert(this, "Sai tên đăng nhập!");
            return;
        } catch (Exception e) {
            MsgBox.alert(this, "Lỗi truy vấn dữ liệu!");
        }
        return;
    }
    
    //Kiểm tra trạng thái tài khoản
    //1.Ném lỗi NullPointerException nếu tài khoản không tồn tại
    //2. Trả về FALSE nếu tài mật khẩu không đúng
    //3.Trả về TRUE nếu tài khoản xác nhận hợp lệ
    public boolean isLogin(String manv, String matKhau) {
        NhanVien nhanVien = dao.selectByID(manv);
        if (nhanVien != null) {
            String matKhau2 = nhanVien.getMatKhau();
            if (matKhau.equals(matKhau2)) {
                return true;
            } else {
                return false;
            }
        } else {
            throw new NullPointerException();
        }
    }
    
    void exit() {
        if (MsgBox.confirm(this, "Bạn có muốn thoát khỏi ứng dụng không?") == 0) {
            System.exit(0);
        }
    }
    
    void hienMatKhau() {
        if (chkHienMK.isSelected()) {
            txtMatKhau.setEchoChar((char) 0);
        } else {
            txtMatKhau.setEchoChar('•');
        }
    }

    /**
     * /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlForm = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblMaNV = new javax.swing.JLabel();
        txtMaNV = new javax.swing.JTextField();
        sprMaNV = new javax.swing.JSeparator();
        lblMatKhau = new javax.swing.JLabel();
        sprMatKhau = new javax.swing.JSeparator();
        txtMatKhau = new javax.swing.JPasswordField();
        btnDangNhap = new javax.swing.JButton();
        chkHienMK = new javax.swing.JCheckBox();
        lblExit = new javax.swing.JLabel();
        lblIcon = new javax.swing.JLabel();
        pnlPhoto = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        lbSlogan = new javax.swing.JLabel();
        lblBlack = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlForm.setBackground(new java.awt.Color(32, 33, 35));

        jPanel2.setBackground(new java.awt.Color(32, 33, 35));

        lblMaNV.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblMaNV.setForeground(new java.awt.Color(57, 113, 177));
        lblMaNV.setText("TÊN ĐĂNG NHẬP");

        txtMaNV.setBackground(new java.awt.Color(32, 33, 35));
        txtMaNV.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtMaNV.setForeground(new java.awt.Color(255, 255, 255));
        txtMaNV.setText("admin");
        txtMaNV.setBorder(javax.swing.BorderFactory.createLineBorder(Contraints.INVISIBLE_COLOR, 7));
        txtMaNV.setCaretColor(null);

        sprMaNV.setForeground(new java.awt.Color(255, 255, 255));

        lblMatKhau.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblMatKhau.setForeground(new java.awt.Color(57, 113, 177));
        lblMatKhau.setText("MẬT KHẨU");

        sprMatKhau.setForeground(new java.awt.Color(255, 255, 255));

        txtMatKhau.setBackground(new java.awt.Color(32, 33, 35));
        txtMatKhau.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtMatKhau.setForeground(new java.awt.Color(255, 255, 255));
        txtMatKhau.setText("123456");
        txtMatKhau.setBorder(javax.swing.BorderFactory.createLineBorder(Contraints.INVISIBLE_COLOR, 7));
        txtMatKhau.setCaretColor(null);
        txtMatKhau.setEchoChar('•');

        btnDangNhap.setBackground(new java.awt.Color(126, 87, 194));
        btnDangNhap.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnDangNhap.setForeground(new java.awt.Color(255, 255, 255));
        btnDangNhap.setText("ĐĂNG NHẬP");
        btnDangNhap.setFocusable(false);
        btnDangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangNhapActionPerformed(evt);
            }
        });

        chkHienMK.setBackground(new java.awt.Color(32, 33, 35));
        chkHienMK.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        chkHienMK.setForeground(new java.awt.Color(57, 113, 177));
        chkHienMK.setText("Hiện mật khẩu");
        chkHienMK.setFocusable(false);
        chkHienMK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkHienMKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sprMaNV)
                    .addComponent(sprMatKhau)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMatKhau)
                            .addComponent(lblMaNV))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(chkHienMK, javax.swing.GroupLayout.DEFAULT_SIZE, 399, Short.MAX_VALUE)
                    .addComponent(btnDangNhap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtMatKhau)
                    .addComponent(txtMaNV))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMaNV)
                .addGap(13, 13, 13)
                .addComponent(txtMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sprMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(lblMatKhau)
                .addGap(13, 13, 13)
                .addComponent(txtMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(sprMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(chkHienMK)
                .addGap(26, 26, 26)
                .addComponent(btnDangNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        lblExit.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblExit.setForeground(new java.awt.Color(57, 113, 177));
        lblExit.setText("X");
        lblExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblExitMouseClicked(evt);
            }
        });

        lblIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/icons/21-avatar-outline (1).gif"))); // NOI18N

        javax.swing.GroupLayout pnlFormLayout = new javax.swing.GroupLayout(pnlForm);
        pnlForm.setLayout(pnlFormLayout);
        pnlFormLayout.setHorizontalGroup(
            pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFormLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFormLayout.createSequentialGroup()
                        .addComponent(lblExit)
                        .addGap(25, 25, 25))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFormLayout.createSequentialGroup()
                        .addGroup(pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42))))
        );
        pnlFormLayout.setVerticalGroup(
            pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFormLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblExit)
                .addGap(18, 18, 18)
                .addComponent(lblIcon)
                .addGap(31, 31, 31)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(72, 72, 72))
        );

        getContentPane().add(pnlForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 0, 520, 650));

        pnlPhoto.setBackground(new java.awt.Color(0, 0, 0));
        pnlPhoto.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setFont(new java.awt.Font("Arial Black", 1, 48)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(57, 113, 177));
        lblTitle.setText("EDUSYS");
        pnlPhoto.add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 280, -1, -1));

        lbSlogan.setBackground(new java.awt.Color(204, 204, 204));
        lbSlogan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbSlogan.setForeground(new java.awt.Color(204, 204, 204));
        lbSlogan.setText("Education Management System");
        pnlPhoto.add(lbSlogan, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 360, -1, -1));

        getContentPane().add(pnlPhoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 650));

        lblBlack.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBlack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/icons/preteen-boy-uses-laptop-make-online-classes-1860x1395 (1).jpg"))); // NOI18N
        getContentPane().add(lblBlack, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseClicked
        // TODO add your handling code here:
        exit();
    }//GEN-LAST:event_lblExitMouseClicked

    private void btnDangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangNhapActionPerformed
        
        login();
    }//GEN-LAST:event_btnDangNhapActionPerformed

    private void chkHienMKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkHienMKActionPerformed
        hienMatKhau();
    }//GEN-LAST:event_chkHienMKActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDangNhap;
    private javax.swing.JCheckBox chkHienMK;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbSlogan;
    private javax.swing.JLabel lblBlack;
    private javax.swing.JLabel lblExit;
    private javax.swing.JLabel lblIcon;
    private javax.swing.JLabel lblMaNV;
    private javax.swing.JLabel lblMatKhau;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel pnlForm;
    private javax.swing.JPanel pnlPhoto;
    private javax.swing.JSeparator sprMaNV;
    private javax.swing.JSeparator sprMatKhau;
    private javax.swing.JTextField txtMaNV;
    private javax.swing.JPasswordField txtMatKhau;
    // End of variables declaration//GEN-END:variables
}
