/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.edusys.ui;

import com.edusys.utils.Contraints;
import com.edusys.utils.XImage;
import java.awt.Color;
import java.awt.Frame;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;
import javax.swing.UIManager;

/**
 *
 * @author Admin
 */
public class GioiThieuJDialog extends javax.swing.JDialog {

    /**
     * Creates new form ChaoDialog
     * @param parent
     * @param model
     */
    public GioiThieuJDialog(Frame parent , boolean model) {
        super(parent,model);
        initComponents();
        init();
    }
    private void init(){      
        this.setLocationRelativeTo(null);
        this.getContentPane().setBackground(Contraints.BG_COLOR);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl = new javax.swing.JLabel();
        lblLogo = new javax.swing.JLabel();
        lblGif = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMouseClicked(evt);
            }
        });
        getContentPane().add(lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 500));

        lblLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/icons/Scholarship  mobile.png"))); // NOI18N
        getContentPane().add(lblLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        lblGif.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/icons/1103-confetti-outline (1).gif"))); // NOI18N
        getContentPane().add(lblGif, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 260, -1, -1));

        jScrollPane1.setBorder(null);

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(0, 52, 75));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea1.setRows(5);
        jTextArea1.setText("Yêu cầu môi trường :\n1. Hệ điều hành bất kì\n2. JDK 1.8 trở lên\n3. SQL SERVER 2008 trở lền\n\nCreation by Dương Tấn Lực \nPS17380/IT16317/Fall2021\nASM SOF2014 \nĐỀ TÀI HỆ THỐNG QUẢN LÝ ĐÀO TẠO EDUSYS\nGiảng Viên : Cao Hoàng Phúc\n");
        jTextArea1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 52, 75), 30));
        jTextArea1.setFocusable(false);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(576, 0, 420, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_formMouseClicked

    private void lblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_lblMouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lbl;
    private javax.swing.JLabel lblGif;
    private javax.swing.JLabel lblLogo;
    // End of variables declaration//GEN-END:variables
}
