/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.edusys.ui;

import com.edusys.utils.Auth;
import com.edusys.utils.BackgroundMenuBar;
import com.edusys.utils.Contraints;
import com.edusys.utils.MsgBox;
import com.edusys.utils.XImage;
import java.awt.Color;
import java.awt.Desktop;
import java.awt.event.ActionEvent;
import java.io.File;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.util.Date;
import javax.swing.Timer;

/**
 *
 * @author Admin
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form EduSysJFrame
     */
    public MainJFrame() {
        initComponents();
        init();
    }

    private void init() {
        this.setLocationRelativeTo(null);
        this.setIconImage(XImage.getAppIcon());
        this.setTitle("HỆ THỐNG QUẢN LÝ ĐÀO TẠO EDUSYS");
        this.getContentPane().setBackground(Contraints.BG_COLOR);  
               
        lblDongHo.setVisible(false);
        startDongHo();
        new ChaoDialog(this, true).setVisible(true);
        new DangNhapJDialog(this, true).setVisible(true);     
        lblMaNV.setText(Auth.USER!=null?Auth.USER.getMaNV():"khách");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTrangThai = new javax.swing.JPanel();
        lblTrangThai = new javax.swing.JLabel();
        lblDongHo = new javax.swing.JLabel();
        pnlToolBar = new javax.swing.JPanel();
        toolBar = new javax.swing.JToolBar();
        btnDangXuat = new javax.swing.JButton();
        btnKetThuc = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JToolBar.Separator();
        btnChuyenDe = new javax.swing.JButton();
        btnNguoiHoc = new javax.swing.JButton();
        btnKhoaHoc = new javax.swing.JButton();
        jSeparator7 = new javax.swing.JToolBar.Separator();
        btnHuongDan = new javax.swing.JButton();
        lblBgToolbar = new javax.swing.JLabel();
        lblImageToolBar = new javax.swing.JLabel();
        pnlCenter = new javax.swing.JPanel();
        lblAPM = new javax.swing.JLabel();
        lblGifClock = new javax.swing.JLabel();
        lblHour = new javax.swing.JLabel();
        lblMinute = new javax.swing.JLabel();
        lblDoubleDot = new javax.swing.JLabel();
        lblSecond = new javax.swing.JLabel();
        lblDay = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        lblDateTimeBox = new javax.swing.JLabel();
        lblHello = new javax.swing.JLabel();
        lblMaNV = new javax.swing.JLabel();
        lblUserBox = new javax.swing.JLabel();
        lblBgCenter = new javax.swing.JLabel();
        lblImageCenter = new javax.swing.JLabel();
        menuBar = new BackgroundMenuBar();
        mnuHeThong = new javax.swing.JMenu();
        mniDangNhap = new javax.swing.JMenuItem();
        mniDangXuat = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mniDoiMatKhau = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        mniKetThuc = new javax.swing.JMenuItem();
        mnuQuanLy = new javax.swing.JMenu();
        mniQLNguoiHoc = new javax.swing.JMenuItem();
        mniQLChuyenDe = new javax.swing.JMenuItem();
        mniQLKhoaHoc = new javax.swing.JMenuItem();
        mniQLHocVien = new javax.swing.JMenuItem();
        jSeparator8 = new javax.swing.JPopupMenu.Separator();
        mniQLNhanVien = new javax.swing.JMenuItem();
        mnuThongKe = new javax.swing.JMenu();
        mniTKNguoiHoc = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        mniTKBangDiem = new javax.swing.JMenuItem();
        mniTKKhoaHoc = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        mniTKDoanhThu = new javax.swing.JMenuItem();
        mnuTroGiup = new javax.swing.JMenu();
        mniHuongDan = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        mniGioiThieu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("HỆ THỐNG QUẢN LÝ ĐÀO TẠO");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        pnlTrangThai.setBackground(Contraints.BG_COLOR);
        pnlTrangThai.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 10, 5, 10));
        pnlTrangThai.setLayout(new java.awt.BorderLayout());

        lblTrangThai.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblTrangThai.setForeground(Contraints.TEXT1_COLOR);
        lblTrangThai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/icons/information.png"))); // NOI18N
        lblTrangThai.setText("Hệ thống quản lý đào tạo");
        pnlTrangThai.add(lblTrangThai, java.awt.BorderLayout.LINE_START);

        lblDongHo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblDongHo.setForeground(Contraints.TEXT1_COLOR);
        lblDongHo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/icons/clock.png"))); // NOI18N
        lblDongHo.setText("00:00:00 AM");
        pnlTrangThai.add(lblDongHo, java.awt.BorderLayout.LINE_END);

        getContentPane().add(pnlTrangThai, java.awt.BorderLayout.PAGE_END);

        pnlToolBar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        toolBar.setBackground(new java.awt.Color(255, 255, 255));
        toolBar.setRollover(true);

        btnDangXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/icons/exit.png"))); // NOI18N
        btnDangXuat.setText("Đăng xuất");
        btnDangXuat.setFocusable(false);
        btnDangXuat.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDangXuat.setMargin(new java.awt.Insets(2, 13, 2, 13));
        btnDangXuat.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangXuatActionPerformed(evt);
            }
        });
        toolBar.add(btnDangXuat);

        btnKetThuc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/icons/stop24.png"))); // NOI18N
        btnKetThuc.setText("Kết thúc");
        btnKetThuc.setFocusable(false);
        btnKetThuc.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnKetThuc.setMargin(new java.awt.Insets(2, 13, 2, 13));
        btnKetThuc.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnKetThuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKetThucActionPerformed(evt);
            }
        });
        toolBar.add(btnKetThuc);
        toolBar.add(jSeparator6);

        btnChuyenDe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/icons/chuyende24.png"))); // NOI18N
        btnChuyenDe.setText("Chuyên đề");
        btnChuyenDe.setFocusable(false);
        btnChuyenDe.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnChuyenDe.setMargin(new java.awt.Insets(2, 13, 2, 13));
        btnChuyenDe.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnChuyenDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChuyenDeActionPerformed(evt);
            }
        });
        toolBar.add(btnChuyenDe);

        btnNguoiHoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/icons/students.png"))); // NOI18N
        btnNguoiHoc.setText("Người học");
        btnNguoiHoc.setFocusable(false);
        btnNguoiHoc.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNguoiHoc.setMargin(new java.awt.Insets(2, 13, 2, 13));
        btnNguoiHoc.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnNguoiHoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNguoiHocActionPerformed(evt);
            }
        });
        toolBar.add(btnNguoiHoc);

        btnKhoaHoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/icons/education.png"))); // NOI18N
        btnKhoaHoc.setText("Khóa học");
        btnKhoaHoc.setFocusable(false);
        btnKhoaHoc.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnKhoaHoc.setMargin(new java.awt.Insets(2, 13, 2, 13));
        btnKhoaHoc.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnKhoaHoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKhoaHocActionPerformed(evt);
            }
        });
        toolBar.add(btnKhoaHoc);
        toolBar.add(jSeparator7);

        btnHuongDan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/icons/help.png"))); // NOI18N
        btnHuongDan.setText("Hướng dẫn");
        btnHuongDan.setFocusable(false);
        btnHuongDan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnHuongDan.setMargin(new java.awt.Insets(2, 13, 2, 13));
        btnHuongDan.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnHuongDan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuongDanActionPerformed(evt);
            }
        });
        toolBar.add(btnHuongDan);

        pnlToolBar.add(toolBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, -1));

        lblBgToolbar.setBackground(new Color(240,240,240,180)
        );
        lblBgToolbar.setOpaque(true);
        pnlToolBar.add(lblBgToolbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 55));

        lblImageToolBar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/icons/blue-sky-with-white-soft-clouds_64749-3051 (1).jpg"))); // NOI18N
        pnlToolBar.add(lblImageToolBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 55));

        getContentPane().add(pnlToolBar, java.awt.BorderLayout.PAGE_START);

        pnlCenter.setOpaque(false);
        pnlCenter.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblAPM.setFont(new java.awt.Font("Agency FB", 0, 48)); // NOI18N
        lblAPM.setForeground(new java.awt.Color(204, 204, 204));
        lblAPM.setText("PM");
        lblAPM.setToolTipText("");
        pnlCenter.add(lblAPM, new org.netbeans.lib.awtextra.AbsoluteConstraints(923, 110, -1, 50));

        lblGifClock.setFont(new java.awt.Font("Agency FB", 0, 70)); // NOI18N
        lblGifClock.setForeground(new java.awt.Color(204, 204, 204));
        lblGifClock.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGifClock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/icons/45-clock-time-outline (1).gif"))); // NOI18N
        lblGifClock.setToolTipText("");
        pnlCenter.add(lblGifClock, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 90, 60, 70));

        lblHour.setFont(new java.awt.Font("Agency FB", 0, 70)); // NOI18N
        lblHour.setForeground(new java.awt.Color(204, 204, 204));
        lblHour.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHour.setText("00");
        lblHour.setToolTipText("");
        pnlCenter.add(lblHour, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 90, 66, 70));

        lblMinute.setFont(new java.awt.Font("Agency FB", 0, 70)); // NOI18N
        lblMinute.setForeground(new java.awt.Color(204, 204, 204));
        lblMinute.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblMinute.setText("00");
        lblMinute.setToolTipText("");
        pnlCenter.add(lblMinute, new org.netbeans.lib.awtextra.AbsoluteConstraints(813, 90, 66, 70));

        lblDoubleDot.setFont(new java.awt.Font("Agency FB", 0, 70)); // NOI18N
        lblDoubleDot.setForeground(new java.awt.Color(204, 204, 204));
        lblDoubleDot.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDoubleDot.setText(":");
        lblDoubleDot.setToolTipText("");
        pnlCenter.add(lblDoubleDot, new org.netbeans.lib.awtextra.AbsoluteConstraints(802, 90, -1, 70));

        lblSecond.setFont(new java.awt.Font("Agency FB", 0, 48)); // NOI18N
        lblSecond.setForeground(new java.awt.Color(204, 204, 204));
        lblSecond.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSecond.setText("00");
        lblSecond.setToolTipText("");
        pnlCenter.add(lblSecond, new org.netbeans.lib.awtextra.AbsoluteConstraints(875, 110, 45, 50));

        lblDay.setFont(new java.awt.Font("Agency FB", 1, 38)); // NOI18N
        lblDay.setForeground(new java.awt.Color(204, 204, 204));
        lblDay.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDay.setText("MONDAY");
        lblDay.setToolTipText("");
        pnlCenter.add(lblDay, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 160, 160, -1));

        lblDate.setFont(new java.awt.Font("Agency FB", 1, 38)); // NOI18N
        lblDate.setForeground(new java.awt.Color(204, 204, 204));
        lblDate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDate.setText("01/01/2021");
        lblDate.setToolTipText("");
        pnlCenter.add(lblDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 160, 160, -1));

        lblDateTimeBox.setBackground(new Color(0,0,0,100));
        lblDateTimeBox.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.gray, java.awt.Color.gray, java.awt.Color.white, java.awt.Color.white));
        lblDateTimeBox.setOpaque(true);
        pnlCenter.add(lblDateTimeBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(655, 80, 340, 140));

        lblHello.setFont(new java.awt.Font("Agency FB", 0, 48)); // NOI18N
        lblHello.setForeground(new java.awt.Color(204, 204, 204));
        lblHello.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHello.setText("Xin chào");
        pnlCenter.add(lblHello, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 180, 70));

        lblMaNV.setFont(new java.awt.Font("Agency FB", 1, 48)); // NOI18N
        lblMaNV.setForeground(new java.awt.Color(204, 204, 204));
        lblMaNV.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMaNV.setText("user");
        pnlCenter.add(lblMaNV, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, 180, 70));

        lblUserBox.setBackground(new Color(0,0,0,100));
        lblUserBox.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.gray, java.awt.Color.gray, java.awt.Color.white, java.awt.Color.white));
        lblUserBox.setOpaque(true);
        pnlCenter.add(lblUserBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 280, 140));

        lblBgCenter.setBackground(new Color(32,33,35,135));
        lblBgCenter.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBgCenter.setOpaque(true);
        pnlCenter.add(lblBgCenter, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 530));

        lblImageCenter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/icons/ezgif.com-gif-maker (1).png"))); // NOI18N
        pnlCenter.add(lblImageCenter, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 530));

        getContentPane().add(pnlCenter, java.awt.BorderLayout.CENTER);

        menuBar.setBackground(new java.awt.Color(0, 0, 102));
        menuBar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        mnuHeThong.setForeground(Contraints.TEXT1_COLOR);
        mnuHeThong.setText("Hệ thống");
        mnuHeThong.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        mnuHeThong.setMargin(new java.awt.Insets(2, 2, 2, 2));
        mnuHeThong.setName(""); // NOI18N
        mnuHeThong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mnuHeThongMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mnuHeThongMouseExited(evt);
            }
        });

        mniDangNhap.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        mniDangNhap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/icons/login24.png"))); // NOI18N
        mniDangNhap.setText("Đăng nhập");
        mniDangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniDangNhapActionPerformed(evt);
            }
        });
        mnuHeThong.add(mniDangNhap);

        mniDangXuat.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.SHIFT_MASK));
        mniDangXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/icons/exit.png"))); // NOI18N
        mniDangXuat.setText("Đăng xuất");
        mniDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniDangXuatActionPerformed(evt);
            }
        });
        mnuHeThong.add(mniDangXuat);
        mnuHeThong.add(jSeparator1);

        mniDoiMatKhau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/icons/lock.png"))); // NOI18N
        mniDoiMatKhau.setText("Đổi mật khẩu");
        mniDoiMatKhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniDoiMatKhauActionPerformed(evt);
            }
        });
        mnuHeThong.add(mniDoiMatKhau);
        mnuHeThong.add(jSeparator2);

        mniKetThuc.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F10, 0));
        mniKetThuc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/icons/stop24.png"))); // NOI18N
        mniKetThuc.setText("Kết thúc");
        mniKetThuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniKetThucActionPerformed(evt);
            }
        });
        mnuHeThong.add(mniKetThuc);

        menuBar.add(mnuHeThong);

        mnuQuanLy.setForeground(Contraints.TEXT1_COLOR);
        mnuQuanLy.setText("Quản lý");
        mnuQuanLy.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        mnuQuanLy.setMargin(new java.awt.Insets(2, 2, 2, 2));
        mnuQuanLy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mnuQuanLyMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mnuQuanLyMouseExited(evt);
            }
        });

        mniQLNguoiHoc.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, java.awt.event.InputEvent.CTRL_MASK));
        mniQLNguoiHoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/icons/students.png"))); // NOI18N
        mniQLNguoiHoc.setText("Người học");
        mniQLNguoiHoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniQLNguoiHocActionPerformed(evt);
            }
        });
        mnuQuanLy.add(mniQLNguoiHoc);

        mniQLChuyenDe.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, java.awt.event.InputEvent.CTRL_MASK));
        mniQLChuyenDe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/icons/chuyende24.png"))); // NOI18N
        mniQLChuyenDe.setText("Chuyên đề");
        mniQLChuyenDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniQLChuyenDeActionPerformed(evt);
            }
        });
        mnuQuanLy.add(mniQLChuyenDe);

        mniQLKhoaHoc.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, java.awt.event.InputEvent.CTRL_MASK));
        mniQLKhoaHoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/icons/education.png"))); // NOI18N
        mniQLKhoaHoc.setText("Khóa học");
        mniQLKhoaHoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniQLKhoaHocActionPerformed(evt);
            }
        });
        mnuQuanLy.add(mniQLKhoaHoc);

        mniQLHocVien.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.CTRL_MASK));
        mniQLHocVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/icons/hocvien.png"))); // NOI18N
        mniQLHocVien.setText("Học Viên");
        mniQLHocVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniQLHocVienActionPerformed(evt);
            }
        });
        mnuQuanLy.add(mniQLHocVien);
        mnuQuanLy.add(jSeparator8);

        mniQLNhanVien.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F5, java.awt.event.InputEvent.CTRL_MASK));
        mniQLNhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/icons/employee.png"))); // NOI18N
        mniQLNhanVien.setText("Nhân viên");
        mniQLNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniQLNhanVienActionPerformed(evt);
            }
        });
        mnuQuanLy.add(mniQLNhanVien);

        menuBar.add(mnuQuanLy);

        mnuThongKe.setForeground(Contraints.TEXT1_COLOR);
        mnuThongKe.setText("Thống kê");
        mnuThongKe.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        mnuThongKe.setMargin(new java.awt.Insets(2, 2, 2, 2));
        mnuThongKe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mnuThongKeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mnuThongKeMouseExited(evt);
            }
        });

        mniTKNguoiHoc.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, java.awt.event.InputEvent.SHIFT_MASK));
        mniTKNguoiHoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/icons/lecture.png"))); // NOI18N
        mniTKNguoiHoc.setText("Người học từng năm");
        mniTKNguoiHoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniTKNguoiHocActionPerformed(evt);
            }
        });
        mnuThongKe.add(mniTKNguoiHoc);
        mnuThongKe.add(jSeparator3);

        mniTKBangDiem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, java.awt.event.InputEvent.SHIFT_MASK));
        mniTKBangDiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/icons/envelop.png"))); // NOI18N
        mniTKBangDiem.setText("Bảng điểm khóa...");
        mniTKBangDiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniTKBangDiemActionPerformed(evt);
            }
        });
        mnuThongKe.add(mniTKBangDiem);

        mniTKKhoaHoc.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, java.awt.event.InputEvent.SHIFT_MASK));
        mniTKKhoaHoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/icons/podium.png"))); // NOI18N
        mniTKKhoaHoc.setText("Điểm từng khóa học");
        mniTKKhoaHoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniTKKhoaHocActionPerformed(evt);
            }
        });
        mnuThongKe.add(mniTKKhoaHoc);
        mnuThongKe.add(jSeparator4);

        mniTKDoanhThu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.SHIFT_MASK));
        mniTKDoanhThu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/icons/money-bag.png"))); // NOI18N
        mniTKDoanhThu.setText("Doanh thu từng chuyên đề...");
        mniTKDoanhThu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniTKDoanhThuActionPerformed(evt);
            }
        });
        mnuThongKe.add(mniTKDoanhThu);

        menuBar.add(mnuThongKe);

        mnuTroGiup.setForeground(Contraints.TEXT1_COLOR);
        mnuTroGiup.setText("Trợ giúp");
        mnuTroGiup.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        mnuTroGiup.setMargin(new java.awt.Insets(2, 2, 2, 2));
        mnuTroGiup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mnuTroGiupMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mnuTroGiupMouseExited(evt);
            }
        });

        mniHuongDan.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        mniHuongDan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/icons/help.png"))); // NOI18N
        mniHuongDan.setText("Hướng dẫn sử dụng");
        mniHuongDan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniHuongDanActionPerformed(evt);
            }
        });
        mnuTroGiup.add(mniHuongDan);
        mnuTroGiup.add(jSeparator5);

        mniGioiThieu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/icons/house.png"))); // NOI18N
        mniGioiThieu.setText("Giới thiệu sản phẩm");
        mniGioiThieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniGioiThieuActionPerformed(evt);
            }
        });
        mnuTroGiup.add(mniGioiThieu);

        menuBar.add(mnuTroGiup);

        setJMenuBar(menuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mniGioiThieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniGioiThieuActionPerformed
        // TODO add your handling code here:
        this.openGioiThieu();
    }//GEN-LAST:event_mniGioiThieuActionPerformed

    private void btnDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangXuatActionPerformed
        // TODO add your handling code here:
        this.dangXuat();
    }//GEN-LAST:event_btnDangXuatActionPerformed

    private void btnKetThucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKetThucActionPerformed
        // TODO add your handling code here:
        this.ketThuc();
    }//GEN-LAST:event_btnKetThucActionPerformed

    private void btnChuyenDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChuyenDeActionPerformed
        // TODO add your handling code here:
        this.openChuyenDe();
    }//GEN-LAST:event_btnChuyenDeActionPerformed

    private void btnNguoiHocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNguoiHocActionPerformed
        // TODO add your handling code here:
        this.openNguoiHoc();
    }//GEN-LAST:event_btnNguoiHocActionPerformed

    private void btnKhoaHocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKhoaHocActionPerformed
        // TODO add your handling code here:
        this.openKhoaHoc();
    }//GEN-LAST:event_btnKhoaHocActionPerformed

    private void btnHuongDanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuongDanActionPerformed
        // TODO add your handling code here:
        this.openHuongDan();
    }//GEN-LAST:event_btnHuongDanActionPerformed

    private void mniDangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniDangNhapActionPerformed
        // TODO add your handling code here:
        this.dangNhap();
    }//GEN-LAST:event_mniDangNhapActionPerformed

    private void mniDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniDangXuatActionPerformed
        // TODO add your handling code here:
        this.dangXuat();
    }//GEN-LAST:event_mniDangXuatActionPerformed

    private void mniDoiMatKhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniDoiMatKhauActionPerformed
        // TODO add your handling code here:
        this.openDoiMatKhau();
    }//GEN-LAST:event_mniDoiMatKhauActionPerformed

    private void mniKetThucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniKetThucActionPerformed
        // TODO add your handling code here:
        this.ketThuc();
    }//GEN-LAST:event_mniKetThucActionPerformed

    private void mniQLNguoiHocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniQLNguoiHocActionPerformed
        // TODO add your handling code here:
        this.openNguoiHoc();
    }//GEN-LAST:event_mniQLNguoiHocActionPerformed

    private void mniQLChuyenDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniQLChuyenDeActionPerformed
        // TODO add your handling code here:
        this.openChuyenDe();
    }//GEN-LAST:event_mniQLChuyenDeActionPerformed

    private void mniQLKhoaHocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniQLKhoaHocActionPerformed
        // TODO add your handling code here:
        this.openKhoaHoc();
    }//GEN-LAST:event_mniQLKhoaHocActionPerformed

    private void mniQLNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniQLNhanVienActionPerformed
        // TODO add your handling code here:
        this.openNhanVien();
    }//GEN-LAST:event_mniQLNhanVienActionPerformed

    private void mniTKNguoiHocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniTKNguoiHocActionPerformed
        // TODO add your handling code here:
        this.openThongKe(1);
    }//GEN-LAST:event_mniTKNguoiHocActionPerformed

    private void mniTKBangDiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniTKBangDiemActionPerformed
        // TODO add your handling code here:
        this.openThongKe(0);
    }//GEN-LAST:event_mniTKBangDiemActionPerformed

    private void mniTKKhoaHocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniTKKhoaHocActionPerformed
        // TODO add your handling code here:
        this.openThongKe(2);
    }//GEN-LAST:event_mniTKKhoaHocActionPerformed

    private void mniTKDoanhThuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniTKDoanhThuActionPerformed
        // TODO add your handling code here:
        this.openThongKe(3);
    }//GEN-LAST:event_mniTKDoanhThuActionPerformed

    private void mniQLHocVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniQLHocVienActionPerformed
        // TODO add your handling code here:
        this.openHocVien();
    }//GEN-LAST:event_mniQLHocVienActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        ketThuc();
    }//GEN-LAST:event_formWindowClosing

    private void mniHuongDanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniHuongDanActionPerformed
        // TODO add your handling code here:
        openHuongDan();
    }//GEN-LAST:event_mniHuongDanActionPerformed

    private void mnuHeThongMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuHeThongMouseEntered
        // TODO add your handling code here:
        mnuHeThong.setForeground(Color.white);
    }//GEN-LAST:event_mnuHeThongMouseEntered

    private void mnuHeThongMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuHeThongMouseExited
        // TODO add your handling code here:
        mnuHeThong.setForeground(Contraints.TEXT1_COLOR);
    }//GEN-LAST:event_mnuHeThongMouseExited

    private void mnuQuanLyMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuQuanLyMouseEntered
        // TODO add your handling code here:
        mnuQuanLy.setForeground(Color.white);
    }//GEN-LAST:event_mnuQuanLyMouseEntered

    private void mnuQuanLyMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuQuanLyMouseExited
        // TODO add your handling code here:
        mnuQuanLy.setForeground(Contraints.TEXT1_COLOR);
    }//GEN-LAST:event_mnuQuanLyMouseExited

    private void mnuThongKeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuThongKeMouseEntered
        // TODO add your handling code here:
        mnuThongKe.setForeground(Color.white);
    }//GEN-LAST:event_mnuThongKeMouseEntered

    private void mnuThongKeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuThongKeMouseExited
        // TODO add your handling code here:
        mnuThongKe.setForeground(Contraints.TEXT1_COLOR);
    }//GEN-LAST:event_mnuThongKeMouseExited

    private void mnuTroGiupMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuTroGiupMouseEntered
        // TODO add your handling code here:
        mnuTroGiup.setForeground(Color.white);
    }//GEN-LAST:event_mnuTroGiupMouseEntered

    private void mnuTroGiupMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuTroGiupMouseExited
        // TODO add your handling code here:
        mnuTroGiup.setForeground(Contraints.TEXT1_COLOR);
    }//GEN-LAST:event_mnuTroGiupMouseExited

    void startDongHo() {
        new Timer(1000, (ActionEvent ae) -> {
            Date now = new Date();
            SimpleDateFormat formater = new SimpleDateFormat("hh:mm:ss a");
            String dongho = formater.format(now);
            SimpleDateFormat formater1 = new SimpleDateFormat("dd/MM/yyyy");
            String date = formater1.format(now);
            lblDongHo.setText(dongho);
            int hour =LocalDateTime.now().getHour();
            int minute =LocalDateTime.now().getMinute();
            int second =LocalDateTime.now().getSecond();
            String apm = hour>=12? "PM":"AM";
            String day =LocalDateTime.now().getDayOfWeek().toString();
            lblHour.setText(hour<10?"0"+hour:hour+"");
            lblMinute.setText(minute<10?"0"+minute:minute+"");
            lblSecond.setText(second<10?"0"+second:second+"");
            lblAPM.setText(apm);
            lblDay.setText(day);
            lblDate.setText(date);
            lblDoubleDot.setVisible(!lblDoubleDot.isVisible());
        }).start();
    }

    void openDoiMatKhau() {
        if (Auth.isLogin()) {
            new DoiMatKhauJDialog(this, true).setVisible(true);
        } else {
            MsgBox.alert(this, "Vui lòng đăng nhập");
        }
    }

    void dangNhap() {
        new DangNhapJDialog(this, true).setVisible(true);
        lblMaNV.setText(Auth.USER!=null?Auth.USER.getMaNV():"khách");
    }

    void dangXuat() {
        Auth.clear();
        new DangNhapJDialog(this, true).setVisible(true);
        lblMaNV.setText(Auth.USER!=null?Auth.USER.getMaNV():"khách");
    }

    void ketThuc() {
        if (MsgBox.confirm(this, "Bạn muốn kết thúc phiên làm việc này") == 0) {
            System.exit(0);
        }
    }

    void openNhanVien() {
        if (Auth.isLogin()) {
            new NhanVienJDialog(this,true).setVisible(true);
        } else {
            MsgBox.alert(this, "Vui lòng đăng nhập");
        }
    }

    void openChuyenDe() {
        if (Auth.isLogin()) {
            new ChuyenDeJDialog(this, true).setVisible(true);
        } else {
            MsgBox.alert(this, "Vui lòng đăng nhập");
        }
    }

    void openNguoiHoc() {
        if (Auth.isLogin()) {
            new NguoiHocJDialog(this, true).setVisible(true);
        } else {
            MsgBox.alert(this, "Vui lòng đăng nhập");
        }
    }

    void openKhoaHoc() {
        if (Auth.isLogin()) {
            new KhoaHocJDialog(this, true).setVisible(true);
        } else {
            MsgBox.alert(this, "Vui lòng đăng nhập");
        }
    }

    void openHocVien() {
        if (Auth.isLogin()) {
            new HocVienJDialog(this,true).setVisible(true);
        } else {
            MsgBox.alert(this, "Vui lòng đăng nhập");
        }
    }

    void openThongKe(int index) {
        if (Auth.isLogin()) {
            if (index == 3 && !Auth.isManager()) {
                MsgBox.alert(this, "Bạn không có quyên xem thông tin doanh thu");
            } else {
                ThongKeJDialog tk = new ThongKeJDialog(this, true);
                tk.selectTab(index);
                tk.setVisible(true);
                
            }
        } else {
            MsgBox.alert(this, "Vui lòng đăng nhập");
        }
    }

    void openHuongDan() {
        try {
            Desktop.getDesktop().browse(new File("help/index.html").toURI());
        } catch (IOException e) {
            MsgBox.alert(this, "Không tìm thấy file hướng dẫn");
        }
    }

    void openGioiThieu() {
        new GioiThieuJDialog(this, true).setVisible(true);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new MainJFrame().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChuyenDe;
    private javax.swing.JButton btnDangXuat;
    private javax.swing.JButton btnHuongDan;
    private javax.swing.JButton btnKetThuc;
    private javax.swing.JButton btnKhoaHoc;
    private javax.swing.JButton btnNguoiHoc;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JToolBar.Separator jSeparator6;
    private javax.swing.JToolBar.Separator jSeparator7;
    private javax.swing.JPopupMenu.Separator jSeparator8;
    private javax.swing.JLabel lblAPM;
    private javax.swing.JLabel lblBgCenter;
    private javax.swing.JLabel lblBgToolbar;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblDateTimeBox;
    private javax.swing.JLabel lblDay;
    private javax.swing.JLabel lblDongHo;
    private javax.swing.JLabel lblDoubleDot;
    private javax.swing.JLabel lblGifClock;
    private javax.swing.JLabel lblHello;
    private javax.swing.JLabel lblHour;
    private javax.swing.JLabel lblImageCenter;
    private javax.swing.JLabel lblImageToolBar;
    private javax.swing.JLabel lblMaNV;
    private javax.swing.JLabel lblMinute;
    private javax.swing.JLabel lblSecond;
    private javax.swing.JLabel lblTrangThai;
    private javax.swing.JLabel lblUserBox;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem mniDangNhap;
    private javax.swing.JMenuItem mniDangXuat;
    private javax.swing.JMenuItem mniDoiMatKhau;
    private javax.swing.JMenuItem mniGioiThieu;
    private javax.swing.JMenuItem mniHuongDan;
    private javax.swing.JMenuItem mniKetThuc;
    private javax.swing.JMenuItem mniQLChuyenDe;
    private javax.swing.JMenuItem mniQLHocVien;
    private javax.swing.JMenuItem mniQLKhoaHoc;
    private javax.swing.JMenuItem mniQLNguoiHoc;
    private javax.swing.JMenuItem mniQLNhanVien;
    private javax.swing.JMenuItem mniTKBangDiem;
    private javax.swing.JMenuItem mniTKDoanhThu;
    private javax.swing.JMenuItem mniTKKhoaHoc;
    private javax.swing.JMenuItem mniTKNguoiHoc;
    private javax.swing.JMenu mnuHeThong;
    private javax.swing.JMenu mnuQuanLy;
    private javax.swing.JMenu mnuThongKe;
    private javax.swing.JMenu mnuTroGiup;
    private javax.swing.JPanel pnlCenter;
    private javax.swing.JPanel pnlToolBar;
    private javax.swing.JPanel pnlTrangThai;
    private javax.swing.JToolBar toolBar;
    // End of variables declaration//GEN-END:variables
}
